import localFont from "next/font/local";
import "./globals.css";
import Header from "./_components/Header";

import Footers from "./_components/Footer";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata = {
  title: "Furniro",
  description: "Generated by Furniro",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body >
        <Header />
        
          {children}
        <Footers />
      </body>
    </html>
  );
}
